#!/usr/bin/ruby -Ku

require 'cgi'
require File.join(File.dirname($0), 'info_reader')

repos_path, output_dir = *ARGV

proc do
  base = File.join(File.dirname($0), '../../')
  repos_path = File.join(base, 'vimperator-plugins.git/') unless repos_path
  output_dir = File.join(base, 'vimpr.github.com.git') unless output_dir
end[]

PREV = '2.3'
Title = 'Vimperator plugins on vimpr'
Langs = %w[ja en-US]
Shorts = {'ja' => 'ja', 'en-US' => 'en'}


def escapeHTML (text)
  CGI.escapeHTML(text)
end

def drop_anchor (text, url)
  "<a href=\"#{url}\">#{escapeHTML(text)}</a>"
end

Langs.each do
  |lang|

  File.open(File.join(output_dir, "plugins-#{Shorts[lang]}.html"), 'w') do
    |file|
    file.puts <<-"EOT"
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html lang="ja">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>#{Title}</title>
    <link rel="stylesheet" type="text/css" href="voqn.css">
  </head>
  <!-- #DO NOT EDIT THIS FILE -->
  <body>
    <h1>#{Title}</h1>
    <table>
      <tr>
        <th>name</th>
        <th>description</th>
        <th>author</th>
        <th>download</th>
      </tr>
    EOT

    plugin_counter = 0
    Dir.glob("#{repos_path}/*.js").sort.each do
      |filename|
      info = PluginInfo.load(filename, lang)
      next unless info
      file.puts <<-"EOT"
      <tr>
        <td>#{
          drop_anchor(
            info.name,
            "http://github.com/vimpr/vimperator-plugins/blob/master/#{File.basename(filename)}"
          )
        }</td>
        <td>#{escapeHTML(info.description)}</td>
        <td>#{info.author}</td>
        <td>
          #{drop_anchor(
            PREV,
            "http://github.com/vimpr/vimperator-plugins/raw/#{PREV}/#{File.basename(filename)}"
          )}
          &nbsp;
          #{drop_anchor(
            "nightly",
            "http://github.com/vimpr/vimperator-plugins/raw/master/#{File.basename(filename)}"
          )}
        </td>
      </tr>
      EOT
      plugin_counter += 1
    end

    file.puts <<-EOT
    </table>
    <p class="plugin-counter">#{plugin_counter} plugins!</p>
    <p class="back-to-top"><a href="./">Back to top</a></p>
  </body>
</html>
    EOT
  end
end
